version: '3'
services:
  testunited-core:
    network_mode: host
    image: "testunited/testunited-core"
    ports:
      - "9001:9001"
    environment:
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:mysql://localhost:3306/testunited
      - spring.datasource.username=springuser
      - spring.datasource.password=testunited_spring
      - LOGBACK_LOG_LEVEL=INFO