apiVersion: apps/v1
kind: Deployment
metadata:
  name: testunited-launcher-deployment
  labels:
    app: testunited-launcher-app
spec:
  selector:
    matchLabels:
      app: testunited-launcher-app
  template:
    metadata:
      labels:
        app: testunited-launcher-app
    spec:
      containers:
      - name: testunited-container
        image: localhost:5000/testunited/testunited-launcher:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: testunited-launcher-service
spec:
  type: NodePort
  selector:
    app: testunited-launcher-app
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
