apiVersion: apps/v1
kind: Deployment
metadata:
  name: testunited-deployment
  labels:
    app: testunited-app
spec:
  selector:
    matchLabels:
      app: testunited-app
  template:
    metadata:
      labels:
        app: testunited-app
    spec:
      containers:
      - name: testunited-container
        image: localhost:32000/testunited/testunited-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testunited-service
spec:
  type: NodePort
  selector:
    app: testunited-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080